package com.dao.bean;
// Generated 2017-9-2 18:43:59 by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Sale generated by hbm2java
 */

public class Sale implements java.io.Serializable {

	private String lsh;
	private String sgs;
	private String name;
	private String sphone;
	private String address;
	private String zffs;
	private String jszt;
	private String jssj;
	private String dhsj;
	private String zje;
	private String srje;
	private String yhje;
	private String czyh;
	private String tlsh;
	private String bz;

	public Sale() {
	}

//	public Sale(String lsh, String name, String sphone) {
//		this.lsh = lsh;
//		this.name = name;
//		this.sphone = sphone;
//	}

	public Sale(String lsh, String sgs, String name, String sphone, 
			    String address, String zffs, String jszt,String jssj, 
			    String dhsj, String zje, String srje, String yhje, 
			    String czyh,String tlsh,String bz) {
		this.lsh = lsh;
		this.sgs = sgs;
		this.name = name;
		this.sphone = sphone;
		this.address = address;
		this.zffs = zffs;
		this.jszt = jszt;
		this.jssj = jssj;
		this.dhsj = dhsj;
		this.zje = zje;
		this.srje = srje;
		this.yhje = yhje;
		this.czyh = czyh;
		this.tlsh = tlsh;
		this.bz = bz;
	}


	public String getLsh() {
		return this.lsh;
	}

	public void setLsh(String lsh) {
		this.lsh = lsh;
	}


	public String getSgs() {
		return this.sgs;
	}

	public void setSgs(String sgs) {
		this.sgs = sgs;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public String getSphone() {
		return this.sphone;
	}

	public void setSphone(String sphone) {
		this.sphone = sphone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZffs() {
		return this.zffs;
	}

	public void setZffs(String zffs) {
		this.zffs = zffs;
	}


	public String getJszt() {
		return this.jszt;
	}

	public void setJszt(String jszt) {
		this.jszt = jszt;
	}


	public String getJssj() {
		return this.jssj;
	}

	public void setJssj(String jssj) {
		this.jssj = jssj;
	}


	public String getDhsj() {
		return this.dhsj;
	}

	public void setDhsj(String dhsj) {
		this.dhsj = dhsj;
	}

	public String getZje() {
		return this.zje;
	}

	public void setZje(String zje) {
		this.zje = zje;
	}


	public String getSrje() {
		return this.srje;
	}

	public void setSrje(String srje) {
		this.srje = srje;
	}


	public String getYhje() {
		return this.yhje;
	}

	public void setYhje(String yhje) {
		this.yhje = yhje;
	}


	public String getCzyh() {
		return this.czyh;
	}

	public void setCzyh(String czyh) {
		this.czyh = czyh;
	}


	public String getTlsh() {
		return this.tlsh;
	}

	public void setTlsh(String tlsh) {
		this.tlsh = tlsh;
	}


	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}
