package com.dao.bean;
// Generated 2017-9-2 18:43:59 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

/**
 * SaleDetail generated by hbm2java
 */

public class TempSaleDetail implements java.io.Serializable {

	private int mxxh;
	private String zblsh;
	private String idm;
	private String dname;
	private String dw;
	private double dj;
	private double chang;
	private double kuang;
	private String gg;
	private double sl;
	private String mblx;
	private double mbdj;
	private double mbzc;
	private String zklx;
	private double zkdj;
	private double zksl;
	private String kklx;
	private double kkdj;
	private double kksl;
	private double zje;
	private String bz;

	public TempSaleDetail() {
	}

	public TempSaleDetail(String zblsh) {
		this.zblsh = zblsh;
	}

	public TempSaleDetail(String zblsh, String idm, String dname, String dw, double dj, double chang,
			double kuang, String gg, double sl, String mblx, double mbdj, double mbzc, String zklx,
			double zkdj, double zksl, String kklx, double kkdj,double kksl, double zje, String bz) {
		this.zblsh = zblsh;
		this.idm = idm;
		this.dname = dname;
		this.dw = dw;
		this.dj = dj;
		this.chang = chang;
		this.kuang = kuang;
		this.gg = gg;
		this.sl = sl;
		this.mblx = mblx;
		this.mbdj = mbdj;
		this.mbzc = mbzc;
		this.zklx = zklx;
		this.zkdj = zkdj;
		this.zksl = zksl;
		this.kklx = kklx;
		this.kkdj = kkdj;
		this.kksl = kksl;
		this.zje = zje;
		this.bz = bz;
	}

	

	public Integer getMxxh() {
		return this.mxxh;
	}

	public void setMxxh(Integer mxxh) {
		this.mxxh = mxxh;
	}

	
	public String getZblsh() {
		return this.zblsh;
	}

	public void setZblsh(String zblsh) {
		this.zblsh = zblsh;
	}


	public String getIdm() {
		return this.idm;
	}

	public void setIdm(String idm) {
		this.idm = idm;
	}


	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}


	public String getDw() {
		return this.dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}


	public double getDj() {
		return this.dj;
	}

	public void setDj(double dj) {
		this.dj = dj;
	}


	public double getChang() {
		return this.chang;
	}

	public void setChang(double chang) {
		this.chang = chang;
	}


	public double getKuang() {
		return this.kuang;
	}

	public void setKuang(double kuang) {
		this.kuang = kuang;
	}


	public String getGg() {
		return this.gg;
	}

	public void setGg(String gg) {
		this.gg = gg;
	}


	public double getSl() {
		return this.sl;
	}

	public void setSl(double sl) {
		this.sl = sl;
	}

	public String getMblx() {
		return this.mblx;
	}

	public void setMblx(String mblx) {
		this.mblx = mblx;
	}


	public double getMbdj() {
		return this.mbdj;
	}

	public void setMbdj(double mbdj) {
		this.mbdj = mbdj;
	}

	
	public double getMbzc() {
		return this.mbzc;
	}

	public void setMbzc(double mbzc) {
		this.mbzc = mbzc;
	}


	public String getZklx() {
		return this.zklx;
	}

	public void setZklx(String zklx) {
		this.zklx = zklx;
	}

	
	public double getZkdj() {
		return this.zkdj;
	}

	public void setZkdj(double zkdj) {
		this.zkdj = zkdj;
	}


	public double getZksl() {
		return this.zksl;
	}

	public void setZksl(double zksl) {
		this.zksl = zksl;
	}


	public String getKklx() {
		return this.kklx;
	}

	public void setKklx(String kklx) {
		this.kklx = kklx;
	}


	public double getKkdj() {
		return this.kkdj;
	}

	public void setKkdj(double kkdj) {
		this.kkdj = kkdj;
	}


	public double getKksl() {
		return this.kksl;
	}

	public void setKksl(double kksl) {
		this.kksl = kksl;
	}


	public double getZje() {
		return this.zje;
	}

	public void setZje(double zje) {
		this.zje = zje;
	}


	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

}
